version: '3'
services:
  web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/apps
    ports:
      - "3000:3000"

        # デバッグ用のポート
      - "1234:1234"
      - "26166:26168"
    tty: true
